### PR TITLE
Added PageController

### PR DESCRIPTION
**Pull request by vijaykarthiktk**
Added PageController to control CupertinoOnboardingPage pages and updated very_good_analysis dependency.

### CODE REVIEW

**Comment by bidica06** [comment]
This is a great addition to this package. I would love to see this on the next version @ivirtex.

**Comment by vijaykarthiktk** [comment]
No problem, just doing my part to make things awesome

**Comment by ivirtex** [comment]
> This is a great addition to this package. I would love to see this on the next version @ivirtex. 

Sure, this is definitely coming in the next version. I'm just waiting for @vijaykarthiktk to apply suggested changes ;)

**Comment by bidica06** [comment]
Thanks guys, this package looks great!

**Comment by ivirtex** [comment]
Added in the newest version :)

**Pull request closed without merging**
